#!/bin/bash

while true; do
    # Data e hora
    DATE=$(date +'%y/%m/%d %R')

    # Temperatura da CPU
    CPU_TEMP=$(sensors | grep -oP 'Package id 0:\s+\+\K[0-9.]+(?=°C)')

    # Wi-Fi com NetworkManager (nmcli)
    WIFI_DEVICE=$(nmcli -t -f DEVICE,TYPE connection show --active | grep wifi | cut -d':' -f1)
    WIFI_SSID=$(nmcli -t -f ACTIVE,SSID dev wifi | grep '^yes' | cut -d':' -f2)
    WIFI_SIGNAL=$(nmcli -t -f IN-USE,SIGNAL dev wifi | grep '^*' | cut -d':' -f2)

    # Status da bateria
    #BATTERY=$(acpi -b | awk '{print $4}' | sed 's/,//')

    # Formatação e saída
    echo "Temp: ${CPU_TEMP}C Wifi: $WIFI_SIGNAL% $DATE"

    # Espera antes de atualizar
    sleep 1
done

